logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-eventlog
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: eventlog-pool
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
